
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bagaaqkmewkuwtudwnqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZ2FhcWttZXdrdXd0dWR3bnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjQwMzIsImV4cCI6MjA1NjI0MDAzMn0.Eu_xDUDDk188oE0dB7W7KJ4oWjB6nQNuUBBnZUMrsvE";

// Enhanced storage management with better fallback handling
const createStorage = () => {
  let storageAvailable = false;
  let memoryStorage: Record<string, string> = {};
  
  try {
    // Test if localStorage is accessible
    const testKey = '__supabase_test__';
    localStorage.setItem(testKey, 'test');
    localStorage.removeItem(testKey);
    storageAvailable = true;
    console.log('localStorage is available for Supabase auth');
  } catch (error) {
    console.warn('localStorage not accessible, using in-memory storage fallback:', error);
    storageAvailable = false;
  }
  
  if (storageAvailable) {
    return {
      getItem: (key: string) => {
        try {
          const item = localStorage.getItem(key);
          console.log('Getting auth item:', key, item ? 'exists' : 'not found');
          return item;
        } catch (error) {
          console.warn('Failed to get item from localStorage:', key, error);
          // Fallback to memory storage
          const memoryItem = memoryStorage[key] || null;
          console.log('Fallback to memory storage:', key, memoryItem ? 'exists' : 'not found');
          return memoryItem;
        }
      },
      setItem: (key: string, value: string) => {
        try {
          console.log('Setting auth item:', key);
          localStorage.setItem(key, value);
          // Also store in memory as backup
          memoryStorage[key] = value;
        } catch (error) {
          console.warn('Failed to set item in localStorage, using memory fallback:', key, error);
          memoryStorage[key] = value;
        }
      },
      removeItem: (key: string) => {
        try {
          console.log('Removing auth item:', key);
          localStorage.removeItem(key);
          delete memoryStorage[key];
        } catch (error) {
          console.warn('Failed to remove item from localStorage:', key, error);
          delete memoryStorage[key];
        }
      }
    };
  } else {
    // Pure in-memory storage fallback
    return {
      getItem: (key: string) => {
        const item = memoryStorage[key] || null;
        console.log('Getting auth item from memory:', key, item ? 'exists' : 'not found');
        return item;
      },
      setItem: (key: string, value: string) => {
        console.log('Setting auth item in memory:', key);
        memoryStorage[key] = value;
      },
      removeItem: (key: string) => {
        console.log('Removing auth item from memory:', key);
        delete memoryStorage[key];
      }
    };
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false,
      storage: createStorage(),
    }
  }
);

// Add global error handler for auth issues
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' && session === null) {
    console.log('User signed out or session expired');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('Auth token refreshed successfully');
  } else if (event === 'SIGNED_IN') {
    console.log('User signed in successfully');
  }
});
